SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+07:00";

CREATE TABLE ARTICLE (
  ARTICLEID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NULL,
  CATEID int(11) NOT NULL,
  ARTICLEIMAGE text COLLATE utf8mb4_vietnamese_ci,
  ARTICLETITLE text COLLATE utf8mb4_vietnamese_ci,
  ARTICLEDESCRIPTION text COLLATE utf8mb4_vietnamese_ci,
  ARTICLECONTENT longtext COLLATE utf8mb4_vietnamese_ci,
  ARTICLECREATIONDATE datetime NULL,
  ARTICLECOUNT int(20) NULL,
  ARTICLEPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  ARTICLETYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (ARTICLEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE CATEGORY (
  CATEID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CAT_CATEID int(5) DEFAULT NULL,
  CATENAME text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATELEVEL int(11) DEFAULT NULL,
  CATEHREF text COLLATE utf8mb4_vietnamese_ci,
  CATEPOSITION int(5) NOT NULL DEFAULT '1',
  CATEPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATETYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (CATEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE INFO (
  INFOID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NULL,
  DEPTID int(5) NULL,
  FACID int(5) NULL,
  SCHID int(5) NULL,
  CATEID int(11) NULL,
  INFODATE text COLLATE utf8mb4_vietnamese_ci,
  INFOTITLE text COLLATE utf8mb4_vietnamese_ci,
  INFOCONTENT longtext COLLATE utf8mb4_vietnamese_ci,
  INFOPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  INFOTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  INFOPUBLICATIONORPERSON tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (INFOID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE USERS (
  USERID varchar(30) NOT NULL,
  DEPTID int(5) NULL,
  FACID int(5) NULL,
  SCHID int(5) NULL,
  USERFULLNAME varchar(254) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  USEREMAIL varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  USERAVATAR text COLLATE utf8mb4_vietnamese_ci NULL,
  USERPOSITION text COLLATE utf8mb4_vietnamese_ci NULL,
  SUBEMAIL varchar(100) COLLATE utf8mb4_vietnamese_ci NULL,
  USERPASSWORD varchar(50) COLLATE utf8mb4_vietnamese_ci NULL,
  USERROLE varchar(255) COLLATE utf8mb4_vietnamese_ci NULL,
  USERTHEME text NOT NULL,
  USERSTATUSSITE tinyint(1) NOT NULL DEFAULT 0,
  USERSTATUS char(10) NULL,
  PRIMARY KEY (USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

INSERT INTO USERS (USERID, DEPTID, FACID, SCHID, USERFULLNAME, USEREMAIL, USERAVATAR, USERPOSITION, USERPASSWORD, USERROLE, USERTHEME, USERSTATUS) VALUES
('ngthuc', NULL, NULL, NULL, 'Nguyên Thức', 'ngthuc@lapvo3.tk', NULL, NULL, '21232f297a57a5a743894a0e4a801fc3', 'admin', 'basic_template', 'approved'),
('ngthuc.hrm', NULL, NULL, NULL, 'HRM Nguyen Thuc', 'ngthuc.hrm@lapvo3.tk', NULL, NULL, NULL, 'user', 'basic_template', 'pending');

CREATE TABLE SYSTEM (
  SYSTEMID int(11) NOT NULL AUTO_INCREMENT,
  SYSTEMTITLE text COLLATE utf8mb4_vietnamese_ci,
  SYSTEMDATA text COLLATE utf8mb4_vietnamese_ci,
  SYSTEMLINK text COLLATE utf8mb4_vietnamese_ci,
  SYSTEMPOLICY varchar(100) COLLATE utf8mb4_vietnamese_ci NULL,
  SYSTEMTYPE varchar(100) COLLATE utf8mb4_vietnamese_ci NULL,
  PRIMARY KEY (SYSTEMID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE MENU (
  MENUID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  MENUPARENT int(5) NULL,
  MENUNAME text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  MENULEVEL int(11) NULL,
  MENUPOSITION int(11) DEFAULT 1,
  MENUTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (MENUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE DEPARTMENT (
  DEPTID int(5) NOT NULL AUTO_INCREMENT,
  PARENTID int(5) NULL,
  DEPTNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTTYPE varchar(10),
  PRIMARY KEY (DEPTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

INSERT INTO DEPARTMENT (DEPTID, PARENTID, DEPTNAME, DEPTENGLISHNAME, DEPTNICKNAME) VALUES
(1, 1, 'Bộ môn Công nghệ phần mềm', 'Department of Software Engineering', 'SE'),
(2, 1, 'Bộ môn Công nghệ thông tin', 'Department of Infomation Technology', 'IT'),
(3, 1, 'Bộ môn Hệ thống thông tin', 'Department of Infomation System', 'IS'),
(4, 1, 'Bộ môn Khoa học máy tính', 'Department of Computer Science', 'CS'),
(5, 1, 'Bộ môn Mạng máy tính và Truyền thông', 'Department of Network and Communication', 'Network'),
(6, 1, 'Bộ môn Tin học ứng dụng', 'Department of Applied Informatics', 'AI'),
(7, 2, 'Bộ môn Kỹ thuật máy tính', 'Department of Computer Engineering', 'CE');

CREATE TABLE FACULTY (
  FACID int(5) NOT NULL AUTO_INCREMENT,
  PARENTID int(5) NULL,
  FACNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  FACENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  FACNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  FACTYPE varchar(10),
  PRIMARY KEY (FACID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

INSERT INTO FACULTY (FACID, PARENTID, FACNAME, FACENGLISHNAME, FACNICKNAME) VALUES
(1, 1, 'Khoa CNTT&TT', 'College of ICT', 'DI'),
(2, 1, 'Khoa Công nghệ', 'College of Engineering Technology', 'CT');

CREATE TABLE SCHOOL (
  SCHID int(5) NOT NULL AUTO_INCREMENT,
  SCHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHTYPE varchar(10),
  PRIMARY KEY (SCHID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

INSERT INTO SCHOOL (SCHID, SCHNAME, SCHENGLISHNAME, SCHNICKNAME) VALUES
(1, 'Đại học Cần Thơ', 'Can Tho University', 'CTU');

ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLECATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLEUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CATEGORYUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOCATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE MENU ADD CONSTRAINT FK_MENUUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERSDEPARTMENT FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERSFACULTY FOREIGN KEY (FACID) REFERENCES FACULTY(FACID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERSSCHOOL FOREIGN KEY (SCHID) REFERENCES SCHOOL(SCHID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFODEPARTMENT FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOFACULTY FOREIGN KEY (FACID) REFERENCES FACULTY(FACID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOSCHOOL FOREIGN KEY (SCHID) REFERENCES SCHOOL(SCHID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENTFACULTY FOREIGN KEY (PARENTID) REFERENCES FACULTY(FACID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE FACULTY ADD CONSTRAINT FK_FACULTYSCHOOL FOREIGN KEY (PARENTID) REFERENCES SCHOOL(SCHID) ON UPDATE CASCADE ON DELETE CASCADE;
