SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+07:00";

CREATE TABLE ARTICLE (
  ARTICLEID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  CATEID int(11) NOT NULL,
  ARTICLEIMAGE text COLLATE utf8mb4_vietnamese_ci,
  ARTICLETITLE text COLLATE utf8mb4_vietnamese_ci,
  ARTICLEDESCRIPTION text COLLATE utf8mb4_vietnamese_ci,
  ARTICLECONTENT longtext COLLATE utf8mb4_vietnamese_ci,
  ARTICLECREATIONDATE datetime DEFAULT NULL,
  ARTICLECOUNT int(20) DEFAULT NULL,
  ARTICLEPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  ARTICLETYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (ARTICLEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE CATEGORY (
  CATEID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CAT_CATEID int(5) DEFAULT NULL,
  CATENAME text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATELEVEL int(11) DEFAULT NULL,
  CATESHOWMENU tinyint(1) DEFAULT NULL,
  CATEPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATETYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (CATEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE INFO (
  INFOID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  CATEID int(11) DEFAULT NULL,
  INFOIMAGE text COLLATE utf8mb4_vietnamese_ci,
  INFODATE text COLLATE utf8mb4_vietnamese_ci,
  INFOTITLE text COLLATE utf8mb4_vietnamese_ci,
  INFODESCRIPTION text COLLATE utf8mb4_vietnamese_ci,
  INFOCONTENT longtext COLLATE utf8mb4_vietnamese_ci,
  INFOPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  INFOTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (INFOID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE MEDIA (
  MEDIAID int(11) NOT NULL AUTO_INCREMENT,
  CATEID int(11) DEFAULT NULL,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  MEDIATITLE text COLLATE utf8mb4_vietnamese_ci,
  MEDIADATA text COLLATE utf8mb4_vietnamese_ci,
  MEDIALINK text COLLATE utf8mb4_vietnamese_ci,
  MEDIAPOLICY varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  MEDIATYPE varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  PRIMARY KEY (MEDIAID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE USERS (
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  USERFULLNAME varchar(254) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  USEREMAIL varchar(100) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTID int(5) DEFAULT NULL,
  FACID int(5) DEFAULT NULL,
  SCHID int(5) DEFAULT NULL,
  USERPASSWORD varchar(50) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  USERROLE varchar(255) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  USERSTATUS char(10) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  PRIMARY KEY (USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

INSERT INTO USERS (USERID, USERFULLNAME, USEREMAIL,DEPTID, FACID, SCHID USERPASSWORD, USERROLE, USERSTATUS) VALUES
('ngthuc', 'Nguyên Thức', 'ngthuc@lapvo3.tk', NULL, NULL, NULL, '21232f297a57a5a743894a0e4a801fc3', 'admin', 'approved'),
('ngthuc.hrm', 'HRM Nguyen Thuc', 'ngthuc.hrm@lapvo3.tk', NULL, NULL, NULL, NULL, 'user', 'pending');

CREATE TABLE SYSTEM (
  SYSTEMID int(11) NOT NULL AUTO_INCREMENT,
  SYSTEMTITLE text COLLATE utf8mb4_vietnamese_ci,
  SYSTEMDATA text COLLATE utf8mb4_vietnamese_ci,
  SYSTEMLINK text COLLATE utf8mb4_vietnamese_ci,
  SYSTEMPOLICY varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  SYSTEMTYPE varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  PRIMARY KEY (SYSTEMID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE MENU (
  MENUID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  MENUPARENT int(5) DEFAULT NULL,
  MENUNAME text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  MENULEVEL int(11) DEFAULT NULL,
  MENUPOSITION int(11) DEFAULT 1,
  MENUTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (MENUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE DEPARTMENT (
  DEPTID int(5) NOT NULL AUTO_INCREMENT,
  PARENTID int(5) DEFAULT NULL,
  DEPTNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  DEPTTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (DEPTID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE FACULTY (
  FACID int(5) NOT NULL AUTO_INCREMENT,
  PARENTID int(5) DEFAULT NULL,
  FACNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  FACENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  FACNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  FACTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (FACID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE SCHOOL (
  SCHID int(5) NOT NULL AUTO_INCREMENT,
  PARENTID int(5) DEFAULT NULL,
  SCHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (SCHID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE SCHOOL (
  SCHID int(5) NOT NULL AUTO_INCREMENT,
  PARENTID int(5) DEFAULT NULL,
  SCHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHENGLISHNAME varchar(200) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHNICKNAME varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  SCHTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (SCHID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLECATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLEUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CATEGORYUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOCATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE MEDIA ADD CONSTRAINT FK_MEDIACATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE MEDIA ADD CONSTRAINT FK_MEDIAUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE MENU ADD CONSTRAINT FK_MENUUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERSDEPARTMENT FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERSFACULTY FOREIGN KEY (FACID) REFERENCES FACULTY(FACID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE USERS ADD CONSTRAINT FK_USERSSCHOOL FOREIGN KEY (SCHID) REFERENCES SCHOOL(SCHID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFODEPARTMENT FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(DEPTID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOFACULTY FOREIGN KEY (FACID) REFERENCES FACULTY(FACID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INFO ADD CONSTRAINT FK_INFOSCHOOL FOREIGN KEY (SCHID) REFERENCES SCHOOL(SCHID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENTFACULTY FOREIGN KEY (PARENTID) REFERENCES FACULTY(FACID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE FACULTY ADD CONSTRAINT FK_FACULTYSCHOOL FOREIGN KEY (PARENTID) REFERENCES SCHOOL(SCHID) ON UPDATE CASCADE ON DELETE CASCADE;
