SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+07:00";

CREATE TABLE ARTICLE (
  ARTICLEID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  CATEID int(11) NOT NULL,
  ARTICLEIMAGE text COLLATE utf8mb4_vietnamese_ci,
  ARTICLETITLE text COLLATE utf8mb4_vietnamese_ci,
  ARTICLEDESCRIPTION text COLLATE utf8mb4_vietnamese_ci,
  ARTICLECONTENT longtext COLLATE utf8mb4_vietnamese_ci,
  ARTICLECREATIONDATE datetime DEFAULT NULL,
  ARTICLECOUNT int(20) DEFAULT NULL,
  ARTICLEPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  ARTICLETYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (ARTICLEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE CATEGORY (
  CATEID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CAT_CATEID int(5) DEFAULT NULL,
  CATENAME text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATENAME_ENGLISH text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATELEVEL int(11) DEFAULT NULL,
  CATESHOWMENU tinyint(1) DEFAULT NULL,
  CATEPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  CATETYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (CATEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE INFO (
  INFOID int(5) NOT NULL AUTO_INCREMENT,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  CATEID int(11) NOT NULL,
  INFOIMAGE text COLLATE utf8mb4_vietnamese_ci,
  INFODATE text COLLATE utf8mb4_vietnamese_ci,
  INFOTITLE text COLLATE utf8mb4_vietnamese_ci,
  INFOTITLE_ENGLISH text COLLATE utf8mb4_vietnamese_ci,
  INFODESCRIPTION text COLLATE utf8mb4_vietnamese_ci,
  INFODESCRIPTION_ENGLISH text COLLATE utf8mb4_vietnamese_ci,
  INFOCONTENT longtext COLLATE utf8mb4_vietnamese_ci,
  INFOCONTENT_ENGLISH longtext COLLATE utf8mb4_vietnamese_ci,
  INFOPOLICY text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  INFOTYPE text COLLATE utf8mb4_vietnamese_ci NOT NULL,
  PRIMARY KEY (INFOID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE MEDIA (
  MEDIAID int(11) NOT NULL AUTO_INCREMENT,
  CATEID int(11) DEFAULT NULL,
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  MEDIATITLE text COLLATE utf8mb4_vietnamese_ci,
  MEDIADATA text COLLATE utf8mb4_vietnamese_ci,
  MEDIALINK text COLLATE utf8mb4_vietnamese_ci,
  MEDIAPOLICY varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  MEDIATYPE varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  PRIMARY KEY (MEDIAID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

CREATE TABLE USERS (
  USERID varchar(30) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  USERPASSWORD varchar(50) COLLATE utf8mb4_vietnamese_ci NOT NULL,
  USERFULLNAME varchar(100) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  USERROLE varchar(255) COLLATE utf8mb4_vietnamese_ci DEFAULT NULL,
  PRIMARY KEY (USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

INSERT INTO USERS (USERID, USERPASSWORD, USERFULLNAME, USERROLE) VALUES
('admin', '21232f297a57a5a743894a0e4a801fc3', 'Quản trị viên', 'admin'),
('ngthuc', '21232f297a57a5a743894a0e4a801fc3', 'Nguyên Thức', 'user');

ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLECATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID);
ALTER TABLE ARTICLE ADD CONSTRAINT FK_ARTICLEUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID);
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CATEGORYUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID);
ALTER TABLE INFO ADD CONSTRAINT FK_INFOCATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID);
ALTER TABLE INFO ADD CONSTRAINT FK_INFOUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID);
ALTER TABLE MEDIA ADD CONSTRAINT FK_MEDIACATEGORY FOREIGN KEY (CATEID) REFERENCES CATEGORY(CATEID);
ALTER TABLE MEDIA ADD CONSTRAINT FK_MEDIAUSERS FOREIGN KEY (USERID) REFERENCES USERS(USERID);
